# Generated by Django 5.0.3 on 2024-11-05 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='image',
        ),
    ]
